### ISSUE TITLE
gnome-flashback menu logo is wrong

### ISSUE THREAD

**Issue by CasualRascal** [EliverLara/Sweet#104]
Hello,
I'm on Fedora 32, gnome-flashback (metacity)
The menu button on the top panel shows the kde plasma icon instead of a gnome icon

P.S. I really love your Sweet project

**Comment by EliverLara** [comment]
Hi, are you sure it's not a problem with the icon theme you use?

**Comment by CasualRascal** [comment]
Hi,
I believe you are right,
I am using your Sweet folders icons, specifically Sweet-Purple-Filled and Sweet-Purple.
