### ISSUE TITLE
Sweet is messing up gnome terminal fyi it works without the theme the theme is great though otherwise thanks in advance

### ISSUE THREAD

**Issue by Framdark** [EliverLara/Sweet#105]
![requestImage](https://user-images.githubusercontent.com/54251138/94471287-7ed7fc80-018e-11eb-85ef-fa27012b4b04.png)

**Comment by EliverLara** [comment]
Hi, could you tell me what is really the issue caused by the theme?

**Comment by Framdark** [comment]
When using the theme enabled text looks all garbled and not applied correctly but when using it without theme enabled terminal works fine, if it works fine on your end then it is something I did I don't know what is exactly causing the issue though.  Thanks for the quick responce

**Comment by thelaughingada** [comment]
Hi, 

I have the same bug on Arch Linux with:
gnome-terminal --version
# GNOME Terminal 3.36.2 using VTE 0.62.0 +BIDI +GNUTLS +ICU  +SYSTEMD
Installed GTK version 3.24.23 
Dark Sweet Theme: (https://github.com/EliverLara/Sweet/releases/download/v1.10.5/Sweet-Dark.zip)
Sweet Theme (latest from master branch)

Here is a screen recording: https://imgur.com/a/1r8btYF 
I started gnome-terminal and you will see the issue. Then I switched to Adwaita Dark Theme and everything is displayed correctly, then back to the Sweet and then to the Sweet dark theme. Unfortunately on the screen recording it is not visible that the Sweet theme has the same issue.
I had to downsample the recording from 4k to 720p to have a smaller filesize, but I can rerecord if needed.

Also the gnome-terminal is the only app with which I have issues.

**Comment by EliverLara** [comment]
Hi @Framdark and @thelaughingada, the issue is not reproducible on my side, but a user commented the following in the `Nordic` theme and I think it could be the same issue you're facing:

> The other day the background in several terminal emulators stopped working if they were configured to use theme colors for foreground/background. I have Nordic-bluish-accent-standard-buttons installed in the latest Arch/Gnome and the background for tilix is black and for gnome-terminal it is 100% transparent. I saw mention of a similar problem in the Arch forums for another theme and the solution was to add a color for text_view_bg. Apparently this is now being used in gtk apps. I modified gtk.css and gtk-dark.css under gtk-3.0 to contain
> 
> @define-color text_view_bg #3b4252;
> 
> immediately after content_view_bg and this fixed the problem. I thought you may want to update your themes accordingly. I have tried other themes but I always come back to bluish/Nordic. Very nice job and thanks for your efforts.

Could you check if this solution works for you?

**Comment by Framdark** [comment]
It somewhat fixes problem the thing is the hex color is the hex color of Nordic so I am going to look for Sweet hex color to use
![Screenshot from 2020-10-03 14-25-21](https://user-images.githubusercontent.com/54251138/95000221-8b8c9400-0584-11eb-85d2-4f892e029d80.png)

**Comment by Framdark** [comment]
I think i got right one going to make pull request now

**Comment by Framdark** [comment]
is there a specific git repo for sweet-dark btw this is happening with all of ur themes

**Comment by Framdark** [comment]
nvm found other branches will do this for all of them since it is such a great theme

**Comment by Framdark** [comment]
#112 #111 #110 #109 #108

**Comment by thelaughingada** [comment]
I can confirm that adding `@define-color text_view_bg` fixes the problem.
