### ISSUE TITLE
Lights in Sweet-Dark

### ISSUE THREAD

**Issue by ThiagoLauter** [EliverLara/Sweet#106]
I don't know if this behave was expected, but in Pop!_OS 20.04 LTS some things don't turn in dark when i using Sweet-Dark:
![Screenshot from 2020-10-02 14-50-38](https://user-images.githubusercontent.com/50457461/94954740-ec9e6400-04bf-11eb-9b0b-13d4b82acbe1.png)
![Screenshot from 2020-10-02 14-55-28](https://user-images.githubusercontent.com/50457461/94954750-ef00be00-04bf-11eb-8a92-faba325fff0a.png)
![Screenshot from 2020-10-02 14-57-06](https://user-images.githubusercontent.com/50457461/94954754-ef995480-04bf-11eb-8bfe-34c2930730a7.png)
![Screenshot from 2020-10-02 13-55-21](https://user-images.githubusercontent.com/50457461/94954765-f32cdb80-04bf-11eb-8fb4-e5a2bb573e7e.png)
![Screenshot ](https://user-images.githubusercontent.com/50457461/94956499-a4cd0c00-04c2-11eb-9474-10c3f789a033.png)

**Comment by EliverLara** [comment]
Hi, please take a look to #93

**Comment by ThiagoLauter** [comment]
works fine
