### ISSUE TITLE
Cannot login lockscreen

### ISSUE THREAD

**Issue by RickyElune** [EliverLara/Sweet#107]
Hi,
I have no password on my manjaro kde. But I cannot unlock the lockscreen. I can login sddm(when system boot) but screenlocking didn't work. 

Thanks.

![photo_2020-10-03_15-15-33](https://user-images.githubusercontent.com/27000147/94985689-4b7cdf80-058b-11eb-813c-9288c29c2ea7.jpg)

**Comment by EliverLara** [comment]
Hi, Does this issue only occur with this theme?

**Comment by RickyElune** [comment]
No, it occurs with all themes. I guess the problem is in the screen locking itself. Thanks.
