### ISSUE TITLE
Sharing via Twitter - Nova

### ISSUE THREAD

**Issue by cdorin93** [EliverLara/Sweet#11]
Hello, 

When I share an article via Twitter, I cannot see what it is written since the background is dark, as well as the letters:

![image](https://user-images.githubusercontent.com/28493662/45916787-10535c00-be5b-11e8-994f-464f1b7323fd.png)

Can this be solved? Or is it from my installation?

P.s. Using Firefox. I do not have this issue on Vivaldi.

**Comment by EliverLara** [comment]
Hi, that's an old firefox issue with dark themes as you can see [here](https://github.com/EliverLara/Ant/issues/25), so I proposed as a temporary solution to install the [Text Contrast for Dark Themes](https://addons.mozilla.org/es/firefox/addon/text-contrast-for-dark-themes/) addon for firefox, so please check if it works for you.

**Comment by cdorin93** [comment]
Super, it works. Thanks !
