### ISSUE TITLE
Can't read the selected line in Gedit.

### ISSUE THREAD

**Issue by major-mayer** [EliverLara/Sweet#114]
Hi,
With the current styling (Sweet Dark Theme) it's pretty hard to read the selected line in Gedit.
For me it looks like this:
![grafik](https://user-images.githubusercontent.com/17907799/95028141-6b50f800-069e-11eb-8825-e104c1c02267.png)

I think this is much too bright and has not enough contrast

**Comment by EliverLara** [comment]
Hi, please take a look to [this issue](https://github.com/dracula/gtk/issues/65)

**Comment by major-mayer** [comment]
thanks for the clarification :+1:
