### ISSUE TITLE
Unable to install sweet dark theme

### ISSUE THREAD

**Issue by sri-vathsa** [EliverLara/Sweet#117]
I am using ubuntu 20 gnome. I cloned this repo in my ~/.themes. The gnome tweaks tool is not showing sweet dark.
![Screenshot from 2020-10-17 19-53-58](https://user-images.githubusercontent.com/53426607/96339484-a269d500-10b2-11eb-8e52-514920270f00.png)
![Screenshot from 2020-10-17 19-54-30](https://user-images.githubusercontent.com/53426607/96339486-a72e8900-10b2-11eb-83e8-30e92757c897.png)

**Comment by Framdark** [comment]
It looks like you cloned the wrong branch this should fix problom run git clone --single-branch --branch nova https://github.com/EliverLara/Sweet.git in ~/.themes
