### ISSUE TITLE
Theme not working with Synaptic Package Manager

### ISSUE THREAD

**Issue by Iorvethe** [EliverLara/Sweet#118]
OS : **Linux Mint 20**
Version of Sweet Dark : **2020-10-25**

## Enhancement

Could it be possible to make this theme also work with the Synaptic Package Manager? Or is it already and I'm doing something wrong? Because on my system Synaptic is in a white theme (probably Mint Y) while everything else is working perfectly. 

![image](https://user-images.githubusercontent.com/58810330/97780160-3c398380-1b83-11eb-9687-7f16b6125508.png)

Does this have something to do with Synaptic requiring root?

Anyway, otherwise the theme is marvellous! Great job with it!

**Comment by EliverLara** [comment]
Hi, for those apps that use `sudo` permissions, you must to install the theme in `/usr/share/themes/`.

**Comment by Iorvethe** [comment]
Yes! That did it. Thanks for your help. I will close the "issue" then.
