### ISSUE TITLE
Window close button is not clear

### ISSUE THREAD

**Issue by NatsumeHill** [EliverLara/Sweet#12]
The line inner window control button too slim

**Comment by EliverLara** [comment]
Hi, what do you mean? I can't see the issue, could you provide a screenshot please?

**Comment by NatsumeHill** [comment]
![screenshot from 2018-10-24 15-36-48](https://user-images.githubusercontent.com/15631570/47414534-c89a5a00-d7a3-11e8-8ad3-28e1a3040409.png)
