### ISSUE TITLE
volume and brightness notification pop-up background not contrast

### ISSUE THREAD

**Issue by asharifauzan** [EliverLara/Sweet#120]
https://ibb.co/c6QpsGH

in the image above when I increase or decrease the volume or the brightness its shows me pop up, but the background of level volume has same color with the background pop-up.
Can u modified it to light color ? thanks anyway

**Comment by EliverLara** [comment]
Hi, Could you provide more info about your OS please?

**Comment by asharifauzan** [comment]
Im using ubuntu mate 20.04 LTS so im forget to write it.

**Comment by EliverLara** [comment]
Fixed!
