### ISSUE TITLE
[Request] Tag a new release?

### ISSUE THREAD

**Issue by epsilon-0** [EliverLara/Sweet#121]
Thanks a lot for this amazing theme package!
I've added the (sweet-dark) package in Gentoo Linux for out users to access easily.
I was wondering if you would be able to create a new release, as I can't use the github version for the Sweet-dark release.

Thanks,
Aisha

**Comment by EliverLara** [comment]
@epsilon-0 The [new release](https://github.com/EliverLara/Sweet/releases/tag/2.0) is ready.

**Comment by epsilon-0** [comment]
Thanks!!
