### ISSUE TITLE
Unable to change order of Close Minimize and Maximize

### ISSUE THREAD

**Issue by cr-trojan23** [EliverLara/Sweet#126]
Hi, I am unable to change the order of the menu buttons. I tried editing the index.theme file located at /usr/share/themes/Sweet from ButtonLayout=minimize,maximize,close to ButtonLayout=:close,maximize,minimize but all in vain.
I have no problem with the buttons when they are located to the right of the window, I need to change the order to close at the left, maximize in the middle and minimize to the right. Please add a few lines of documentation for this.

**Comment by EliverLara** [comment]
Hi, that configuration must be done through the system, the easiest way is using a `tweaktool` for your system, or you could try using the command line.

**Comment by ronilaukkarinen** [comment]
It's weird, I have title bar buttons in the left side in Electron apps, but in Nautilus and Terminal they are on the right. Any idea why? Tweaktool settings make no difference. GTK-4? Some apps use GTK-3? I'm clueless...

**Comment by ronilaukkarinen** [comment]
> It's weird, I have title bar buttons in the left side in Electron apps, but in Nautilus and Terminal they are on the right. Any idea why? Tweaktool settings make no difference. GTK-4? Some apps use GTK-3? I'm clueless...

[Solved](https://mementomori.social/@rolle/115315710232970116).

> This was solved on ubuntu forums. Turns out I had to log into Budgie, then use the desktop settings there to move the controls to the left...then logged back in to ubuntu and it's all fixed now.
