### ISSUE TITLE
Changing 'Accent' color?

### ISSUE THREAD

**Issue by Nightmare247** [EliverLara/Sweet#127]
Hi, thanks for the amazing theme. I wanted to know if there was a way to change the purple 'accent' color to some color of my choice. If you don't understand what i mean by the purple color, I've included some screenshots:

![image](https://user-images.githubusercontent.com/65822218/103200240-d9f6c800-4912-11eb-9926-9f77471f07c5.png)

![image](https://user-images.githubusercontent.com/65822218/103200270-e549f380-4912-11eb-9a30-4000edefa413.png)

Thank you

**Comment by SpacePuppeh** [comment]
I have the same exact request. I like darker colors and changes on the sweet dark, but I like the accent color of mars much better. I like orange a lot.

If I could swap the theme color to that, I would love it.

If the dev could add a tutorial on how to change the theme colors for the Firefox theme as well as the desktop theme that'd be great. :)

**Comment by EliverLara** [comment]
Hi, those are elements of the `gnome-shell` theme, so, you must open the `gnome-shell/_colors.scss` file and  change the colors of `$g1` and `$g2` variables, then just recompile the theme using [sass](https://sass-lang.com/install).

**Comment by Nightmare247** [comment]
@EliverLara there doesn't seem to be any _colors.css file in `Sweet-Ambar/gnome-shell`, I see a gnome-shell.css, but that does not have the variables $g1 and $g2

**Comment by sgse** [comment]
Hello, 
first, thank you, a wonderful theme.
second ;-)
`gnome-shell/_colors.scss`
```
$g1: #00e8b7;
$g2: #00e8b7;
```
Is just "green", both. From screenshot, it must be ~ #ce0cbf to #6326a4.
I only wish to change this small part :-)
greetings.

**Comment by EliverLara** [comment]
The `.scss` files are available under this repo, so you must clone it.

**Comment by sgse** [comment]
I did before I post.

![image](https://user-images.githubusercontent.com/17575778/113925891-d0231180-97eb-11eb-8e30-788af3c46d90.png)

 gnome-shell/_colors.scss $g1 and $g2 is the same. Or is "The .scss files" different from _colors.scss?
 Before I learn sass I will change the theme ;-)
Seems you can close this issue.

Thanks again for your really nice work.

**Comment by TangdizhiH** [comment]
> 

Sorry to reply on this closed issue, but I would really like to get some instructions on how to compile the Sweet-v40 dark with a customized accent color. I really like this theme and especially the accent color of the light sweet, at the mean time I want it to be a complete dark theme. 

It will be appreciated if you can have some instruction on compiling the theme cuz the instruction from sass itself is not sufficient for outsider to understand the mechanism. BTW, thank you again for you great work!
