### ISSUE TITLE
Logout screen is empty.

### ISSUE THREAD

**Issue by withmask** [EliverLara/Sweet#128]
The logout screen (when hitting the power button or choosing to shutdown/restart/logout) does not show any buttons with the Sweet KDE theme. Only a blur but no buttons to choose. Currently running on `Ubuntu 20.04.1 LTS x86_64`

PS: Great work on the theme.

**Comment by EliverLara** [comment]
Related to [ #26](https://github.com/EliverLara/Sweet-kde/issues/26) on the kde port.
