### ISSUE TITLE
Theme are not applied on some elements

### ISSUE THREAD

**Issue by ElephantsDad** [EliverLara/Sweet#132]
Theme are not applied on some elements: notification panel at the top, dock panel, calendar. Same after I restarted the system.  

Info:  
Ubuntu 18.04.5 LTS  
GNOME Shell 3.28.4  
Theme files placed in `/usr/share/themes`, activated with gnome tweak tool.  

![Снимок экрана от 2021-01-19 18-25-21](https://user-images.githubusercontent.com/30314740/105007429-b7744c80-5a83-11eb-9af7-14e3899030de.png)

**Comment by EliverLara** [comment]
Hi, it looks like you haven't applied the gnome-shell theme.
