### ISSUE TITLE
Ubuntu dark mode incompatibility

### ISSUE THREAD

**Issue by felipedelta0** [EliverLara/Sweet#134]
The theme doesn't seem to properly set the OS on dark theme.
Since Ubuntu Dark Theme was implemented on the OS, it have a dark theme on the top bar menus, but with the theme up and running, the dark elements doesn't work very well.

As an example, the following menu should be on dark mode, but with the theme running, it doesn't
![Screenshot from 2021-01-25 12-29-45](https://user-images.githubusercontent.com/10116449/105726703-1b29ca00-5f09-11eb-8d70-11fe913b2f80.png)

**Comment by EliverLara** [comment]
Hi, it looks like you haven't applied the gnome-shell theme.
