### ISSUE TITLE
Check mark don't render when i turn it one

### ISSUE THREAD

**Issue by TheMadMaker2** [EliverLara/Sweet#138]
![default](https://user-images.githubusercontent.com/64815956/107885004-c9e87700-6ec5-11eb-8c8c-ac0c0367ed78.png)
![Sweet-dark](https://user-images.githubusercontent.com/64815956/107885005-ca810d80-6ec5-11eb-9ca1-f489961f839f.png)
I dont know how to properly describe this
Im Runing a arch and xfce

**Comment by EliverLara** [comment]
Hi @TheMadMaker2, Are you using a Hidpi monitor?

**Comment by TheMadMaker2** [comment]
Yes

**Comment by TheMadMaker2** [comment]
thanks for fixing it I really like the sweet theme
