### ISSUE TITLE
VS Code icon not working

### ISSUE THREAD

**Issue by moghaazi** [EliverLara/Sweet#139]
![image](https://user-images.githubusercontent.com/49992538/108029163-ad6b4c80-7035-11eb-99b3-63fbae9b346b.png)

Also add icon for **MS Edge** browser and **Alacrity** terminal

**Comment by Fraser-Hobbs** [comment]
I'm Having same issue with VS Code Icon.

**Comment by EliverLara** [comment]
Please take a look to [#72](https://github.com/EliverLara/candy-icons/issues/72) , [#76](https://github.com/EliverLara/candy-icons/issues/76) or [#79](https://github.com/EliverLara/candy-icons/issues/79) on the main candy-icons repo.
