### ISSUE TITLE
Sweet Dark Theme Notification Text is hard to read

### ISSUE THREAD

**Issue by oae** [EliverLara/Sweet#14]
Hi,

As it can be seen in screenshot, dark theme notifications are hard to read. I am using Gnome 3.30.1 on Ubuntu 18.10

![image](https://user-images.githubusercontent.com/1043714/48314731-8a43ce00-e5de-11e8-9ac8-1b8659a91f5b.png)

**Comment by EliverLara** [comment]
Hi, I think that's related to #6, could you please check if that solution works for you as well?

**Comment by oae** [comment]
Yaru aka Communitheme is installed by default on 18.10. So there are no session choice in gdm to select it. My current workaround is 
```css
.notification-banner * {
  color: white;
}
```
