### ISSUE TITLE
Unable to install SDDM theme or Global Theme since last update

### ISSUE THREAD

**Issue by ATragicEnding** [EliverLara/Sweet#140]
I tried to install Sweet KDE Global theme on KDE Neon today but I keep getting the error :

Installation of /tmp/XNzHWn-Sweet.tar.xz failed: Could not install dependency: 'kns://sddmtheme.knsrc/api.kde-look.org/1334945'

Installation of SDDM theme alone returns a "Connection Closed" error.

**Comment by clickonrefresh** [comment]
I have the same issue. sweet is not even showing up in global themes. Have tried on various operating systems.

**Comment by EliverLara** [comment]
That was a bug with the opendesktop server and has been fixed.
