### ISSUE TITLE
Theme not applying on login screen. Pop OS 20.10

### ISSUE THREAD

**Issue by TheJarmanitor** [EliverLara/Sweet#142]
Hello.

i've set up the theme on Pop OS 20.10 with gnome, but i noticed the theme is not applied on the first login screen. it still uses the default theme. I've read a bit and i think it's because gnome now uses ".gresource" files to set it up. can you help me set the login screen correctly?

**Comment by EliverLara** [comment]
Hi, I'm sorry but this theme doesn't provide any login screen theming.
