### ISSUE TITLE
What color scheme is used?

### ISSUE THREAD

**Issue by epsilon-0** [EliverLara/Sweet#148]
Could you please give an small outline of the color schemes used so that we can use that for other softwares, like inside emacs/spacemacs and kitty and others.

Thanks a lot :heart:

**Comment by EliverLara** [comment]
Hi, you can see all the used color [here](https://github.com/EliverLara/Sweet/blob/master/gtk-3.0/_colors.scss).

**Comment by epsilon-0** [comment]
thanks a lot!
