### ISSUE TITLE
No differentiation for inactive pane in Nemo

### ISSUE THREAD

**Issue by AndreiMiculita** [EliverLara/Sweet#150]
Hello,

The Nemo file manager can navigate with 2 panes at once. In the Mint-Y theme, the currently active pane is brighter than the other pane. Well, actually the inactive pane is darker.

This theme unfortunately does not define a separate background for the inactive pane, so it's impossible to tell which pane is active. I think it should be a different, darker color than the active pane.

Below you find the CSS selector for the background of the inactive pane, and setting it to black to give an example:

```
.nemo-window .nemo-inactive-pane .view, .nemo-window .nemo-inactive-pane iconview {
  background-color: #000000; }
```

![Screenshot from 2021-04-26 21-49-49](https://user-images.githubusercontent.com/6352172/116141715-576ff080-a6d9-11eb-9d92-c662906e9bff.png)

**Comment by EliverLara** [comment]
Thanks for the trick, fixed with d8da5a5 .
