### ISSUE TITLE
Transparent mouse right button menu on Firefox

### ISSUE THREAD

**Issue by chipotledonut** [EliverLara/Sweet#151]
As seen in this image:

Firefox: 90.0a1 (2021-05-03) (64-bit)
Ubuntu 20.04

![Screenshot from 2021-05-04 08-52-20](https://user-images.githubusercontent.com/67786790/116969197-5cb6d780-aca5-11eb-88f1-54239a62df01.png)

**Comment by rakaw** [comment]
I'm also having the same issue.

Info:
Firefox: 90.0a1 (2021-05-04) (64-bit)
Garuda Linux
Gnome-shell version 1:40.0+67+g79acae417-1


Adawaita & Adwaita-dark  are fine, with opaque backgrounds.

**Comment by rakaw** [comment]
@chipotledonut  It look's like this bug has been resolved by mozilla: [Bug 1709719](https://bugzilla.mozilla.org/show_bug.cgi?id=1709719#c3)
