### ISSUE TITLE
Titlebar doesn't blurred

### ISSUE THREAD

**Issue by RMTT** [EliverLara/Sweet#158]
Hello, i use this theme and everything works well except the titlebar and login/out page.
+ titlebar: not blurred
![image](https://user-images.githubusercontent.com/20596599/123510393-c653d080-d6ad-11eb-8ab2-70aaa1bbcaf5.png)
+ login/out page: the button not blurred(maybe)
![image](https://user-images.githubusercontent.com/20596599/123510315-51809680-d6ad-11eb-9cfe-d1c4189e14a3.png)

I install the global theme using KDE system setting and the kvantuam theme using the archive file from https://store.kde.org/p/1294013/
![image](https://user-images.githubusercontent.com/20596599/123510363-9a384f80-d6ad-11eb-8178-966579e76c7a.png)

Hope to solve above two problems

**Comment by EliverLara** [comment]
Hi, to get a blurred titlebar you must select `Sweet-Dark-transparent` in `system settings > appearance > window decorations`.
On  login/out page I don't see any issue.
