### ISSUE TITLE
How to set theme variants?

### ISSUE THREAD

**Issue by mrusme** [EliverLara/Sweet#159]
Sorry to ask questions here, but maybe you could add the `gsettings` commands required to set the theme variants? I tried setting `Sweet-dark` and `Sweet:dark` but neither seem to have worked.

Thank you!

**Comment by mrusme** [comment]
For everyone else wondering: This get repo consists of different branches for each variant. A simplye `git checkout mars` has helped with setting the dark variant.

**Comment by msr8** [comment]
I dont understand, could you please elaborate?
