### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by Nokou-Sen** [EliverLara/Sweet#16]
Hello there am having a trouble with the icons and i cant figure out why
The folder file shows the icon exactly like the ones in the photo but on me when I set the icon theme the icons look like ubuntu is there anything I should change?
 
![screenshot from 2018-11-23 14 50 46](https://user-images.githubusercontent.com/45289576/48944462-6dd55900-ef2f-11e8-80dd-0d930ebbe9a7.png)
![screenshot from 2018-11-23 14 52 26](https://user-images.githubusercontent.com/45289576/48944463-6dd55900-ef2f-11e8-9be2-59075b1157a2.png)

**Comment by EliverLara** [comment]
Hi, did you move the downloaded icon folder  to `~/.icons/` or `/usr/share/icons/`?

**Comment by JAicewizard** [comment]
what folder do I have to copy? I cant find any instructions on how to get the icons to work at all. I cant find the icon folder either
