### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by Trqhxrd** [EliverLara/Sweet#164]
Hi! First I want to say, that this theme is awesome! I love it.
I am currently customizing my i3 and want to use your theme.
Is there a color palette so I can customize my discord and other i3 colors to match the theme?

Kind regards, 
Trqhxrd

**Comment by EliverLara** [comment]
Hi, sorry for the late response, you can find all the colors used in this theme inside the `gtk-3.0/_colors.scss` file.

**Comment by ralyodio** [comment]
i have literally thousands of directories on my system with 'gtk-3.0' in the path
