### ISSUE TITLE
Explorer issue

### ISSUE THREAD

**Issue by AlanMejia10** [EliverLara/Sweet#17]
![screenshot from 2018-12-08 19-06-44](https://user-images.githubusercontent.com/45723972/49692320-23520000-fb1d-11e8-9c2b-2ae0b05365db.png)

this is the issue  I was taking about, it only happens with vs code, hope you can fix it, Ill be glad to invite you a coffee, you're making a great job, keep it up

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, could you privide more info about your OS please?
