### ISSUE TITLE
Suggestion: Add current keyboard layout name to the lockscreen

### ISSUE THREAD

**Issue by Kriper1111** [EliverLara/Sweet#175]
I have several different keyboard layouts installed and when I try unlocking, the selected layout sometimes differs from the one I used to make my password. Which leads to me typing the right keys in a wrong layout and observing "Password Incorrect" message for at least 15 seconds, before I'm able to retype the password in the correct layout. A small text display with the current keyboard layout would be really nice to have.

**Comment by EliverLara** [comment]
Hi, it actually shows your current layout:

![distri](https://user-images.githubusercontent.com/9838260/142779234-5d5a8298-89b0-4ea2-b195-1f8b3413afcf.png)

**Comment by Kriper1111** [comment]
It must be a broken install for me then, since there's nothing there in my case.
![no layout](https://user-images.githubusercontent.com/31844440/142878363-7207d4b4-a45a-4095-b46e-9461c05f1009.png)

I should note that I'm using KDE Plasma and not Gtk-based DE.
There might be something wrong with the Look and Feel variant of it, on [nova branch](https://github.com/EliverLara/Sweet/tree/nova/kde/look-and-feel), since the button shows up when default Breeze is selected and that is Look and Feel.

After doing some in-depth research I've come to a conclusion that the culprit might be [this](https://github.com/EliverLara/Sweet/blob/123dd8b452c7f7becbb48cb44365053c99c72c5f/kde/look-and-feel/contents/components/KeyboardLayoutButton.qml#L55) line of code. Changing `(layout.isInitialized() && layout.layoutsList[layout.layout].displayName)` to just `layout.currentLayoutDisplayName` worked fine for me. *I should maybe PR this..?*
