### ISSUE TITLE
Problems with lock screen

### ISSUE THREAD

**Issue by RoyvanEmpel** [EliverLara/Sweet#179]
Hello!

I have installed the Sweet KDE Theme on my (k)Ubuntu 20.04 LTS install and ran into a problem. The theme looks great and everything is working except for the lockscreen.

When I press Meta + L to lock the system locks but there is no UI and I'm not able to unlock it.
![image](https://user-images.githubusercontent.com/47390057/141613955-c0de6bdb-d77f-4169-aed7-c50f4bf79ae5.png)

Renaming the `lockscreen` folder in `.local/share/plasma/look-and-feel/Sweet/contents/` 'fixes' the problem and shows the normal lock screen again. Are there any logs that I can send wich may help in figuring out the problem?

Specs:
Plasma: 5.18.5
OS: Ubuntu 20.04.3 LTS x86_64 
Kernel: 5.11.0-40-generic
CPU: AMD Ryzen 9 5900X (24) @ 3.700GHz
GPU: NVIDIA GeForce GTX 1060 6GB (470.57.01)

**Comment by EliverLara** [comment]
Hi, Could you test if [this](https://github.com/EliverLara/Sweet-kde/issues/24#issuecomment-821895717) solution works for you, please?

**Comment by EliverLara** [comment]
Fixed with 9eebdbe10b3a0e6c7d277227201c55bbb5ab46cb
