### ISSUE TITLE
Using `Sweet-Mars` applications theme causes selected folder / file icons to black out

### ISSUE THREAD

**Issue by yenson-lau** [EliverLara/Sweet#18]
Running Ubuntu 18.04, Gnome 3.

Interestingly this issue only occurs on the window that is in focus, otherwise it behaves normally.

**In focus**:
![screenshot from 2018-12-11 22-52-28](https://user-images.githubusercontent.com/6440007/49846109-aaaaa800-fd97-11e8-88f2-9b162ae8afc6.png)

**Not in focus**:
![screenshot from 2018-12-11 22-53-48](https://user-images.githubusercontent.com/6440007/49846124-bd24e180-fd97-11e8-9e58-80d1b33db766.png)

**Comment by rqmok** [comment]
I am having this same issue under Solus OS Budgie.
