### ISSUE TITLE
Kvantum folder missing capital K

### ISSUE THREAD

**Issue by ShayBox** [EliverLara/Sweet#181]
Connected to my last issue https://github.com/EliverLara/Sweet/issues/78

The kvantum folder needs to be capitalized Kvantum to match the actual location name of Kvantum

And everything from my last issue still stands, this repo is hardly install-able without a script to rename and move everything.

**Comment by EliverLara** [comment]
Hi, in 123dd8b452c7f7becbb48cb44365053c99c72c5f I've renamed the folder to match the system folder.
