### ISSUE TITLE
A color might be too light in Sweet Ambar

### ISSUE THREAD

**Issue by yadelei** [EliverLara/Sweet#19]
Hi Lara, thanks for your working, I really like your themes, it's really nice!
I'm using the Sweet Ambar (downloaded from gnome-look.org, version 1.5.1) on my system(Ubuntu 18.04, Gnome 3.28), and I think there is maybe a problem.

**There is a color might be too light in Sweet Ambar (as figures), that courses some problems, such as not clear to read, and seems like disabled.**

![sweet](https://user-images.githubusercontent.com/20869032/50039621-16c72d80-0070-11e9-8723-5a8cbc6165e2.png)
![sweet](https://user-images.githubusercontent.com/20869032/50039580-8983d900-006f-11e9-80d3-5c1165e34fdf.png)

**Comment by EliverLara** [comment]
Fixed!
