### ISSUE TITLE
GTK4 support

### ISSUE THREAD

**Issue by tsbarnes** [EliverLara/Sweet#190]
I love this theme so much, but it bothers me that GTK4 apps (like the Extensions app) use the default Adwaita. Is there any chance of a GTK4 version of Sweet (especially nova)?

**Comment by Virepri** [comment]
Seconded. Willing to throw 25$ out on a bounty.

**Comment by EliverLara** [comment]
Hi. I'm sorry for the very late response, this theme already provides support for gtk4, anyway, if you're using the latest gnome versions(wich use libadwaita) [this](https://github.com/odziom91/libadwaita-theme-changer) should work as a temporary solution
