### ISSUE TITLE
Can't recognize the radio button and checkbox.

### ISSUE THREAD

**Issue by Jay-flow** [EliverLara/Sweet#191]
I applied the theme and I can't see radio button and checkbox. The same goes for all versions of other colors.

https://user-images.githubusercontent.com/29420674/158028698-568c9eba-2a48-4734-8795-7fed093742d6.mp4

# Environments

***xfce4-panel 4.16.3 (Xfce 4.16)***

![image](https://user-images.githubusercontent.com/29420674/158053370-c5cfcab1-3273-490d-b92b-b9170dccab90.png)

**Comment by Jay-flow** [comment]
https://github.com/EliverLara/Nordic/issues/168#issuecomment-1024449370

It's work for me!

**Comment by mulder-fbi** [comment]
I had the same issue. It was caused by the "Add" function of the Xfce appearance app. It does not install the `assets` folder contained in the theme. The solution for me was to manually extract the content of the theme to `~/.themes/Sweet-Dark-v40/` and "reload" the theme in the appearance app.

**Comment by humanplayer2** [comment]
@Jay-flow, did you copy `gtk(-dark).css` to `~/.config/gtk-3.0` to override libadwaita? If so, then you should also copy the theme's `assets` folder to `.config`, as the `.css` looks for the bullet/checkbox graphics in  `../assets`.

**Comment by LynxUtz** [comment]
How did you do it ?
That's don't appear correctly on my PC.
I'm on Debian 11 with Xfce 4.16 (the latest).
