### ISSUE TITLE
Question: What software have you used to create printscreen

### ISSUE THREAD

**Issue by felipetesc** [EliverLara/Sweet#195]
Hello. This is not a bug post. I could not find the correct place to ask. I only want to know what software have You used to create the picture from https://www.gnome-look.org/p/1253385/ :  I mean the window gallery:
![gallery](https://user-images.githubusercontent.com/2336812/167476780-1f6b35d4-16fa-4a67-a3a6-30e44e1b14fc.jpg)

**Comment by EliverLara** [comment]
Hi, sorry for the late response, if you still need it it is `called gtk3-widget-factory`.

**Comment by felipetesc** [comment]
> Hi, sorry for the late response, if you still need it it is `called gtk3-widget-factory`.

Yes, I search for it. Thanks.
