### ISSUE TITLE
What are the nova and mars branches?

### ISSUE THREAD

**Issue by Samisafool** [EliverLara/Sweet#198]
They have gnome-related commits but there's a kde version in there? It's not clear what they are and the readme isn't very extensive. Could you please tell me what the structure of the repo is?

Why even have multiple branches if there will be multiple gtk versions anyway?

**Comment by EliverLara** [comment]
Hi, the `nova` and `mars` as well as the `Ambar` and `Ambar-Blue` branches are "variants" of the main theme, that is, they follow the same style line as the main theme but with different color palettes.

**Comment by EliverLara** [comment]
By now just sweet-dark (nova) and mars variants have a kde version.

**Comment by Samisafool** [comment]
And sorry for bothering, but one last question. What is the https://github.com/EliverLara/Sweet-kde repo for?

**Comment by EliverLara** [comment]
That repo contains the plasma theme for kde
