### ISSUE TITLE
add pop os icon

### ISSUE THREAD

**Issue by YoussofKhawaja** [EliverLara/Sweet#199]
pop os logo not found
![image](https://user-images.githubusercontent.com/84130367/172139075-9160d112-48bc-4a63-b262-5581fa14d2c4.png)

**Comment by KiwihSushi** [comment]
I actually got the Pop Icon in the About and the Support section.
![image](https://user-images.githubusercontent.com/59313923/173191883-caf4ff59-0f30-4cf7-872c-b3d67d4901f4.png)
