### ISSUE TITLE
status bar/top bar has wrong colors

### ISSUE THREAD

**Issue by thwayant** [EliverLara/Sweet#209]
entire theme works fine, the only issue is the colors in top bar are incorrect.
![Screenshot from 2022-08-31 13-12-42](https://user-images.githubusercontent.com/112543050/187622022-96966fd7-f476-4ac6-8166-a7a49faec3c9.png)
![Screenshot from 2022-08-31 13-13-02](https://user-images.githubusercontent.com/112543050/187622035-1b6f555a-2db6-4f28-a2f8-a8305340cf46.png)

**Comment by humanplayer2** [comment]
It look well on my end with a day-date download of Sweet-Dark-v40 from [the Gnome-look page](https://www.gnome-look.org/p/1253385/).

What theme are you applying?

**Comment by thwayant** [comment]
The issue was on, As I am new to Linux, I installed gnome 40 theme while my
gnome version was 42.

**Comment by humanplayer2** [comment]
@thwayant , OK, so the issue is resolved? Then perhaps you can "close with comment"?

**Comment by thwayant** [comment]
Ok 👍
