### ISSUE TITLE
Calculator, Calendar, Store and Settings windows do not change themes

### ISSUE THREAD

**Issue by ncl427** [EliverLara/Sweet#210]
Greetings.

I am running Fedora 36, and using the sweet-dark v40 theme. (Very nice theme by the way)

Most of the system is using the theme, but a few windows remain un-theme, mainly the ones from the title of this post.

Is there any solution for this?

Thank you

**Comment by humanplayer2** [comment]
Try copying the `gtk.css` and `dark-gtk.css`  from the theme's `gtk-3.0` and `gtk-4.0` folders to `~/.config/gtk-3.0` and `~/.config/gtk-4.0`, respectively.
