### ISSUE TITLE
Support for GNOME 43?

### ISSUE THREAD

**Issue by Leniwcowaty** [EliverLara/Sweet#211]
Hello there.
Will you be adding support for GNOME 43? With GTK4 and new quick settings menu. Currently you can get GNOME 43 with Ubuntu 22.10 and Fedora 37 Beta.
Cheers!

**Comment by D3vil0p3r** [comment]
I have same needs, for Arch Linux GNOME 43. Let's hope ^^

**Comment by D3vil0p3r** [comment]
@JurijOrlow Sorry for the double comment. I have a workaround for you:

Download the Sweet theme you wish, for example I downloaded from gnome-extensions site the Sweet-Dark (https://www.gnome-look.org/p/1253385/ -> File -> Sweet-Dark.tar.xz)

Then, extract the content and you will get the folder "Sweet-Dark". Move this folder in `$HOME/.themes/` or `/usr/share/themes` folder. Let's guess you moved to `$HOME/.themes` folder. Then run:
```
mkdir -p "${HOME}/.config/gtk-4.0"
ln -sf "$HOME/.themes/Sweet-Dark/assets" "${HOME}/.config/gtk-4.0/assets"
ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
```
Verify that the created links are not broken, and try to open the File Manager for checking if it is working well.

**Comment by javisxo** [comment]
@JurijOrlow All its working fine for me in GNOME 43, i only need to edit a few lines in the gtk-dark.css to make it work and get the theme function right with the gtk-4.0.

**Comment by D3vil0p3r** [comment]
> @JurijOrlow All its working fine for me in GNOME 43, i only need to edit a few lines in the gtk-dark.css to make it work and get the theme function right with the gtk-4.0.

In this way I guess that the only "remaining issue" is that the buttons on the top-right when you click the Power Button:
![image](https://user-images.githubusercontent.com/83867734/201477179-f507c25d-f33d-4417-8481-099be8769772.png)

they remain with default color as this image.

**Comment by javisxo** [comment]
This is how its looks for me using ubuntu22.10
![image](https://user-images.githubusercontent.com/63229513/201525039-580dafc8-4ee0-4418-9fa6-520013708987.png)
![image](https://user-images.githubusercontent.com/63229513/201525093-c8e3c311-125e-4119-87e6-c767594538c1.png)
 Im trying to fix  but I have no idea about this though haha

**Comment by D3vil0p3r** [comment]
> This is how its looks for me using ubuntu22.10 ![image](https://user-images.githubusercontent.com/63229513/201525039-580dafc8-4ee0-4418-9fa6-520013708987.png) ![image](https://user-images.githubusercontent.com/63229513/201525093-c8e3c311-125e-4119-87e6-c767594538c1.png) Im trying to fix but I have no idea about this though haha

Maybe we need to wait for @EliverLara

**Comment by XPLegend** [comment]
> @JurijOrlow Sorry for the double comment. I have a workaround for you:
> 
> Download the Sweet theme you wish, for example I downloaded from gnome-extensions site the Sweet-Dark (https://www.gnome-look.org/p/1253385/ -> File -> Sweet-Dark.tar.xz)
> 
> Then, extract the content and you will get the folder "Sweet-Dark". Move this folder in `$HOME/.themes/` or `/usr/share/themes` folder. Let's guess you moved to `$HOME/.themes` folder. Then run:
> 
> ```
> mkdir -p "${HOME}/.config/gtk-4.0"
> ln -sf "$HOME/.themes/Sweet-Dark/assets" "${HOME}/.config/assets"
> ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
> ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
> ```
> 
> Verify that the created links are not broken, and try to open the File Manager for checking if it is working well.
> 
> I add a dumb question. On https://www.gnome-look.org/p/1253385/ there are files with suffix v40 (I guess GNOME v40) and other files without it. The files without v40 are intended for GNOME 3.x or for GNOME > 40 ? (i.e., 41, 42)?

I used your commands but for me is still broken, what do I do?

**Comment by Korothi** [comment]
> > @JurijOrlow Sorry for the double comment. I have a workaround for you:
> > Download the Sweet theme you wish, for example I downloaded from gnome-extensions site the Sweet-Dark (https://www.gnome-look.org/p/1253385/ -> File -> Sweet-Dark.tar.xz)
> > Then, extract the content and you will get the folder "Sweet-Dark". Move this folder in `$HOME/.themes/` or `/usr/share/themes` folder. Let's guess you moved to `$HOME/.themes` folder. Then run:
> > ```
> > mkdir -p "${HOME}/.config/gtk-4.0"
> > ln -sf "$HOME/.themes/Sweet-Dark/assets" "${HOME}/.config/assets"
> > ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
> > ln -sf "$HOME/.themes/Sweet-Dark/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Verify that the created links are not broken, and try to open the File Manager for checking if it is working well.
> > I add a dumb question. On https://www.gnome-look.org/p/1253385/ there are files with suffix v40 (I guess GNOME v40) and other files without it. The files without v40 are intended for GNOME 3.x or for GNOME > 40 ? (i.e., 41, 42)?
> 
> I used your commands but for me is still broken, what do I do?

make sure links are correct, folder is usually sweet-dark-v40 (at least for me)
once you do that, reboot will make it work :)
![image](https://user-images.githubusercontent.com/88345690/207548145-95406649-6fee-43db-b360-00a773b8d626.png)
