### ISSUE TITLE
Theme is not applied to all windows under Gnome 43?

### ISSUE THREAD

**Issue by sickboy101** [EliverLara/Sweet#214]
In Fedora 37 + Gnome 43 the theme is not applied to all windows. What am I missing?

![sweetdark](https://user-images.githubusercontent.com/118892599/203519415-00f22386-0a83-4407-8976-7b044a244647.png)

**Comment by XPLegend** [comment]
Same problem with me and I have no idea why, I am honestly surprise that the upper bar works for you, mine doesn't :(

**Comment by EliverLara** [comment]
@sickboy101 For those windows you could try using [this](https://github.com/odziom91/libadwaita-theme-changer).
@XPLegend Are you using the correct version of the theme for your OS?

**Comment by XPLegend** [comment]
@EliverLara I am using sweet-v40, but I even tried sweet-classic download via dnf, same thing

**Comment by sickboy101** [comment]
> @sickboy101 For those windows you could try using [this](https://github.com/odziom91/libadwaita-theme-changer). 

That did the trick for me, thanks!

**Comment by Mr-Stetson** [comment]
Copying `gtk-3.0` and `gtk-4.0` dirs to `~/.config` and merging fixed this for me
