### ISSUE TITLE
Latest Sweet theme in Xfce4 having hard to read text for Warnings

### ISSUE THREAD

**Issue by maboleth** [EliverLara/Sweet#219]
Text in the Trash folder and warnings of all kinds are hardly readable.

I'd much appreciate the change of that fluorescent color to something more visible.

Theme is otherwise working correctly.

![Screenshot_2023-01-12_23-13-24](https://user-images.githubusercontent.com/2467520/212193154-72b0d6a9-8525-445f-835e-aef6abd3fa02.png)
![Screenshot_2023-01-12_23-13-59](https://user-images.githubusercontent.com/2467520/212193159-cf7f724b-d7e7-43d6-acdc-1c938b3bc4cd.png)

**Comment by EliverLara** [comment]
Fixed with 670c20d034891ad026cba75253ae139e7c570093
