### ISSUE TITLE
Accent color is not purple like in screenshots

### ISSUE THREAD

**Issue by TheSunCat** [EliverLara/Sweet#220]
Hi! I've cloned this theme from git and installed it, however the accent color is not the purple one I get from the AUR package of this same theme, `sweet-gtk-theme-dark`. Has the accent color changed since commit `123dd8b452c7f7becbb48cb44365053c99c72c5f`?
For reference, this is what it looks like in `nwg-look` (gtk3 app):
![image](https://user-images.githubusercontent.com/44881120/212484227-ff9e650f-7a05-462f-91a4-f276ad3097b4.png)

**Comment by TheSunCat** [comment]
I have pulled the latest commit and can confirm this is still the case. I'm happy to test anything if needed, though I am no longer using the Sweet theme, so if this issue only affects me then I wouldn't mind closing it :)

**Comment by shailgohil** [comment]
The same issue with me, the theme colour is not purple 
OS : Fedora  38
![2023-05-15_17-02](https://github.com/EliverLara/Sweet/assets/14279649/435445d4-e164-46d7-9e3b-f212570081b2)
![2023-05-15_17-01](https://github.com/EliverLara/Sweet/assets/14279649/4a847926-47d5-43f4-93fb-135ccaefb44e)

**Comment by blackxored** [comment]
Same issue here, almost a year later, anywhere I could look?

**Comment by EliverLara** [comment]
Hi,Are you using tht right theme variant (`Sweet-Dark`) from [gnome-look](https://www.gnome-look.org/p/1253385/)?

**Comment by blackxored** [comment]
I’m previewing with nwg-look and yes all apps I can try open with green accents. —Best Regards,Adrian Perezhttps://adrianperez.codesOn Aug 2, 2024, at 11:29 AM, Eliver L. ***@***.***> wrote:﻿
Hi,Are you using tht right theme variant (Sweet-Dark) from gnome-look?

**Comment by EliverLara** [comment]
> I’m previewing with nwg-look

I'm not referring nwg-look, I'd like to know  whether you downloaded the `Sweet-Dark.tar.xz `file from [this site](https://www.gnome-look.org/p/1253385/) or from other site

**Comment by blackxored** [comment]
So apparently the one in the AUR is broken, the one from the releases page seems to work correctly, my apologies.
