### ISSUE TITLE
Weird dots in Xfce systray

### ISSUE THREAD

**Issue by maboleth** [EliverLara/Sweet#221]
![Untitled](https://user-images.githubusercontent.com/2467520/212570231-193ef9b3-2dc3-410b-8f8e-cc6f0f6f98de.png)

When using this theme sometimes weird dots are above each item in menu bar.

When enlarged (as in the image above) it looks like they are rounded menu buttons.

**Comment by EliverLara** [comment]
Fixed with [2d0138e](https://github.com/EliverLara/Sweet/commit/2d0138e306815bca3c9a8db6bab9284a383ebebf)
