### ISSUE TITLE
title bar fonts goes blurry on 150% scaled screen

### ISSUE THREAD

**Issue by elhananjair** [EliverLara/Sweet#223]
Hello @EliverLara I love sweet theme so much but I am having a problem with it, I scaled the screen to 150% and all windows title bar fonts go blurry.

![image](https://user-images.githubusercontent.com/69236638/213905966-73185350-79b0-44f0-bf74-d2eb2597b0c6.png)

**Comment by EliverLara** [comment]
Hi, does it only happen  with the sweet theme?

**Comment by elhananjair** [comment]
Sorry that I didn't reply earlier, I think is not a sweet problem this issue is found on all custom themes on KDE, therefore, it is an issue of KDE it self.
