### ISSUE TITLE
Everything works super good but the Dock seems broken

### ISSUE THREAD

**Issue by 5ug4md** [EliverLara/Sweet#225]
![image](https://user-images.githubusercontent.com/73983080/221400555-61d199db-7be7-4f99-b00d-e02962c2f3c4.png)
distro Ubuntu 22.04 jammy
gnome GNOME Shell 42.5

**Comment by 5ug4md** [comment]
![image](https://user-images.githubusercontent.com/73983080/221400773-dfc361fc-2451-4679-a4f1-3334226f97ae.png)
the application menu is also same

**Comment by EliverLara** [comment]
It seems you're using a wrong version of the theme for your DE, please make sure you're using the latest version released on [gnome-look](https://www.gnome-look.org/p/1253385)

**Comment by 5ug4md** [comment]
thankyou it worked <3
