### ISSUE TITLE
appears a weird black background around app docs/taskbar

### ISSUE THREAD

**Issue by ixaman** [EliverLara/Sweet#229]
Hi there! I am using sweet dark everything seems fine but it adds a weird dark background around the app docks.
I am using ubuntu 22.04 with gnome 42.5

**Comment by musa-fernanda** [comment]
something similar happens with xfce4-panel too

**Comment by EliverLara** [comment]
HI, Could you provide a screenshot please?

**Comment by musa-fernanda** [comment]
> HI, Could you provide a screenshot please?

![Screenshot_2023-05-10_14-22-15](https://github.com/EliverLara/Sweet/assets/116525237/b4b7d491-8522-4a53-b170-5fb0a717b6e9)

![Screenshot_2023-05-10_14-22-58](https://github.com/EliverLara/Sweet/assets/116525237/e9cb12b7-0522-40e5-9951-26a9a80525fe)

**Comment by EliverLara** [comment]
@musa-fernanda do you refer to the red outline in the panel?

**Comment by musa-fernanda** [comment]
> @musa-fernanda do you refer to the red outline in the panel?
yes
