### ISSUE TITLE
Thin borders for separation between windows

### ISSUE THREAD

**Issue by kaustabpal** [EliverLara/Sweet#23]
I love the dark theme however lack of any borders causes trouble in navigating. This theme will be the perfect dark theme if you can add borders.
[https://imgur.com/a/xwBVHF7](url)
If you notice this screenshot, you will see that the tweaks window when placed on top of the file explorer window almost mixes with the file explorer window because there is no visual separation between the two windows. Maybe adding a thin white border around the windows might help in this issue.
[https://imgur.com/a/M4iiW31](url)
Maybe something like this white border that chrome has. 
P.S> This border appears only with chrome and no other apps.

**Comment by EliverLara** [comment]
I don't like how borders look in a window, instead I've darken windows shadows to add visual separation between them.

| Before  | After |
| ------------- | ------------- |
| ![captura de pantalla de 2019-01-02 16-12-10](https://user-images.githubusercontent.com/9838260/50665410-374f1d00-0f76-11e9-9f7b-77846e5f80f9.png) | ![captura de pantalla de 2019-01-02 16-11-49](https://user-images.githubusercontent.com/9838260/50665419-3ddd9480-0f76-11e9-907e-179e24c45284.png)|

**Comment by kaustabpal** [comment]
Perfect. Thanks a lot. :)
