### ISSUE TITLE
"Holes" at XFCE panel systray icons

### ISSUE THREAD

**Issue by R0CK1NG0D** [EliverLara/Sweet#231]
I'm having this bug after boot or reboot. To "reduce it" i need to switch to other theme and switch again back, but just receive a small holes. It most apeears with light wallpapers and the darks "camuflize" they.
![Captura de tela_2023-04-19_18-53-47](https://user-images.githubusercontent.com/131310051/233209716-5771b023-29e0-4bb0-b024-0dc344dc1abc.png)

**Comment by EliverLara** [comment]
Fixed with [2d0138e](https://github.com/EliverLara/Sweet/commit/2d0138e306815bca3c9a8db6bab9284a383ebebf)
