### ISSUE TITLE
Issue with styling

### ISSUE THREAD

**Issue by Coder2195Text** [EliverLara/Sweet#233]
Using Ubuntu 23.04 Lunar Lobster
Sound looks full all the time
![image](https://user-images.githubusercontent.com/63069499/234390441-f99e5ec8-efdd-42d5-97b5-6bc82718a3a1.png)

Some stuff doesn't work 
![image](https://user-images.githubusercontent.com/63069499/234390513-704b4bb7-b579-4e90-9fed-433ed8dc0230.png)

**Comment by Coder2195Text** [comment]
> Hi, Are you using any gnome-shell extension?

Yes

https://askubuntu.com/questions/1464716/upgraded-to-23-04-and-issues-with-shell-themes/1465548#1465548 

This seems to be the issue, is it possible to upgrade to gnome 44

**Comment by EliverLara** [comment]
That seems to be an issue with some of your extensions, could you provide the name of your installed extensions?

**Comment by Coder2195Text** [comment]
I fixed it via git cloning the repo instead of downloading from the release

So it seems the extensions are fine

So at the end I think the releases are outdated or that I downloaded an
outdated release
