### ISSUE TITLE
No change my file windows

### ISSUE THREAD

**Issue by JasubiPL** [EliverLara/Sweet#236]
Hi, when apply the theme, just change my settings windows, but no change the windows files how in the image, 

![image](https://github.com/EliverLara/Sweet/assets/114939324/acba7542-9d82-4413-a6cf-932db4fd2c4c)

![image](https://github.com/EliverLara/Sweet/assets/114939324/6e95ca4f-df22-423d-b1ae-304846375979)

**Comment by EliverLara** [comment]
Please try using [this](https://github.com/odziom91/libadwaita-theme-changer)
