### ISSUE TITLE
Theme applies everywhere but on the power off panel.

### ISSUE THREAD

**Issue by Millsy021** [EliverLara/Sweet#237]
For some reason the I cannot get the theme to apply to the power off drop down panel.

![Screenshot from 2023-05-29 14-40-29](https://github.com/EliverLara/Sweet/assets/134944742/ad93ad8a-0db1-4a75-84a8-0cf1ce5ca90f)

Thanks for the hopeful help in advance.

**Comment by EliverLara** [comment]
Hi, Could you provide more info about your system please?

**Comment by Millsy021** [comment]
Hi, I am using Manjaro Linux on Gnome 44.1

**Comment by Millsy021** [comment]
the new update fix the issue, thank you.
