### ISSUE TITLE
Libadwaita apps under KDE unthemed

### ISSUE THREAD

**Issue by TechXero** [EliverLara/Sweet#238]
Applying GTK theme under KDE not working for Libadwaita apps. Sorry if this has been already reported. How to fix? Same for Nordic. 

Thanks

**Comment by EliverLara** [comment]
Please try using [this](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by TechXero** [comment]
@EliverLara Thanks for reply. I have tried that saw it in your reply for Gnome 43 issue. Sadly it didn't work. All it did was break theming more for GTK4 apps. I think you need to make an install script or something that puts files in right place and does the symlinks. Like with Layan-GTK theme by Vince and many others.

**Comment by EliverLara** [comment]
This is odd, it actually works for me:
![Screenshot_20230530_171705](https://github.com/EliverLara/Sweet/assets/9838260/85346659-3f78-4bca-8b26-3dd29c590445)

Could you check  your symlinks aren't broken under `~/.config/gtk-4.0 `?

**Comment by TechXero** [comment]
All I did was Git clone the gtk theme into ~/.local/share/themes/ and ran that Python script you sent. Check Libadwaita apps they still using default theme.
