### ISSUE TITLE
Can window frame be changed of color for focused windows?

### ISSUE THREAD

**Issue by warcayac** [EliverLara/Sweet#240]
Details of my OS:
``` 
OS: EndeavourOS Linux x86_64 
Kernel: 6.4.1-zen1-1-zen 
DE: Plasma 5.27.6 
WM: KWin 
WM Theme: Sweet-Dark-transparent 
Theme: [Plasma], Sweet-Dark [GTK2/3] 
Icons: [Plasma], candy-icons [GTK2/3] 
``` 
I've installed Kvantum from AUR and I set Sweet as Theme there, I changed `Reduce window opacity by` to 30%, no more changes.

The appearance is nice, but i am having trouble discerning the windows so I want the frame of the focused (active) window to have a highlighted color. This does not exist in System Settings nor in Kvantum, I have modified kdeglobals with this:
``` 
kwriteconfig5 --file ~/.config/kdeglobals --group WM --key frame 61,174,233
kwriteconfig5 --file ~/.config/kdeglobals --group WM --key inactiveFrame  239,240,241
``` 

but no change desired, it seems your theme has restrictions on it. How can I change frame color for the focused window?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the very late response, I'm not sure whether it could be achieved or not since aurorae has lots of resctrictions, but you could try by modifying the window decoration files stored under `.local/share/aurorae/theme-name`
