### ISSUE TITLE
gtk4: No property named "height"

### ISSUE THREAD

**Issue by ProspectPyxis** [EliverLara/Sweet#242]
Whenever a gtk4 app is run from the command line, this error message appears:

```
Theme parser error: gtk.css:5606:3-9: No property named "height"
```

Related: #125

**Comment by EliverLara** [comment]
Fixed with [ee4be9e](https://github.com/EliverLara/Sweet/commit/ee4be9efb84c87881dfc3e4455fd84823e76b287)
