### ISSUE TITLE
[Sweet Mars] GTK-4 Theme not working

### ISSUE THREAD

**Issue by blacktoz** [EliverLara/Sweet#243]
Hey, reinstalled arch not 2 days ago, I installed the Mars variant of your theme, which contains gtk-4 files, but when applying it manually or with the libadwaita theme changer [](https://github.com/odziom91/libadwaita-theme-changer)
The gtk.css gets overwritten by this, so gtk-4 apps like nautilus will still have the default theme (renamed with .txt extension for github) : 
[gtk.css.txt](https://github.com/EliverLara/Sweet/files/12455048/gtk.css.txt)
What can I do ?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, Are you still getting this issue?
