### ISSUE TITLE
GNOME 45 Theme Support

### ISSUE THREAD

**Issue by D3vil0p3r** [EliverLara/Sweet#244]
@EliverLara Your Sweet Themes will support GNOME 45 that should be released in September?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response,  this theme actually provides support for libadwaita since a long time ago, the best option to get it working with libadwita is by using [this script](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by D3vil0p3r** [comment]
Cannot be implemented built-in on the theme?

**Comment by EliverLara** [comment]
> Cannot be implemented built-in on the theme?

It would be actually the same since you'll need to run an extra script to make it fully work
