### ISSUE TITLE
No libadwaita support

### ISSUE THREAD

**Issue by cheebamba** [EliverLara/Sweet#246]
Hi,

Love this theme, buit lately I've changed to fedora 38, and some apps are not respecting theme becasue of libadwaita.
Will there be support for libadwaita?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response,  this theme actually provides support for libadwaita since a long time ago, the best option to get it working with libadwita is by using [this script](https://github.com/odziom91/libadwaita-theme-changer)
