### ISSUE TITLE
[Sweet and Sweet Ambar Blue] Top panel in default global theme layout does not extend completely

### ISSUE THREAD

**Issue by win8linux** [EliverLara/Sweet#248]
When using the desktop layout from the Sweet and Sweet Ambar Blue global themes in KDE Store, the top panel is not fully extended:
![Screenshot_20231023_232652](https://github.com/EliverLara/Sweet/assets/11584387/2105d8d3-1e9e-4a90-944a-5c9e7b525f3c)

### System details
Operating System: Arch Linux 
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11

**Comment by EliverLara** [comment]
Hi, I'm sorry but those themes don't provide an official desktop layout
