### ISSUE TITLE
GNOME 45, not full customization

### ISSUE THREAD

**Issue by Jakson2023** [EliverLara/Sweet#250]
Good evening! I don't know the reason, but my nautilus is not customizable. The part where the folders are located changes the background color. And everything else remains unchanged.
![Screenshot from 2023-11-12 19-13-43-1](https://github.com/EliverLara/Sweet/assets/125270235/44dd16dc-ea5b-4653-877f-7984cd34a8c6)

**Comment by EliverLara** [comment]
Hi, the best way to get it wotking with libadwaita is by using [this script](https://github.com/odziom91/libadwaita-theme-changer)
