### ISSUE TITLE
Sweet forces Light theme in Cinnamon

### ISSUE THREAD

**Issue by MinecraftDocker** [EliverLara/Sweet#253]
Hey all!
I am currently using the Sweet theme in Linux Mint Cinnamon.
I have applied the theme under the Applications, Icons, and Desktop tabs in the Themes settings.  However, when I apply the "Sweet" theme to the Applications, it forces Light mode.  There is no Sweet-dark app theme.  Additionally, if i apply the "mint-Y-Dark-Blue" theme, it does go into dark mode.  When I enter the "Simplified" settings area, the Light/Dark mode switch is greyed out.
Do I need to download the Dark theme from somewhere, or is this a bug?

**Comment by EliverLara** [comment]
Hi, yes, the latest version are released on [gnome-look](https://www.pling.com/p/1253385/), there are the files for all the theme variants :)

**Comment by MinecraftDocker** [comment]
@EliverLara 
Thanks.
Just curious, what is the difference between the Sweet-dark and Sweet-dark-v40?
