### ISSUE TITLE
Update GitHub Release

### ISSUE THREAD

**Issue by D3vil0p3r** [EliverLara/Sweet#256]
Hello @EliverLara I know that in gnomelook there are already the final archives of the theme available.

Since on Linux fetchers to make packages GitHub Release is often used, could you please update the latest archives you produced about the theme also in GitHub Release please?

**Comment by D3vil0p3r** [comment]
Hello @EliverLara Any news about this?

**Comment by EliverLara** [comment]
Hi, @D3vil0p3r  I've just launch a new release https://github.com/EliverLara/Sweet/releases/tag/v4.0

**Comment by D3vil0p3r** [comment]
Thank you very much!
