### ISSUE TITLE
QUESTION: difference between standard and v40 version

### ISSUE THREAD

**Issue by D3vil0p3r** [EliverLara/Sweet#257]
What is the difference between Sweet standard theme (like Sweet-Dark.tar.xz) and v40 version (like Sweet-Dark-v40.tar.xz)?

**Comment by D3vil0p3r** [comment]
So @EliverLara for GNOME 45 do we need -v40?

PS: could you please give a look to https://github.com/EliverLara/Sweet/issues/256 ?

**Comment by EliverLara** [comment]
> So @EliverLara for GNOME 45 do we need -v40?

Yes, that's the version that provides the correct support
