### ISSUE TITLE
Question how to change panel border color.

### ISSUE THREAD

**Issue by dukeofsoftware** [EliverLara/Sweet#258]
Hi!  am using a sweet dark theme it is really beautiful. But at the panel there is a white weird border. When I use another theme it is gone. How can I change border colors?
![image](https://github.com/EliverLara/Sweet/assets/89215036/e3c07702-1063-491f-9cf8-263d719f53b8)
![image](https://github.com/EliverLara/Sweet/assets/89215036/da37aee5-e20a-469a-9d60-a1e9059b62bf)

**Comment by EliverLara** [comment]
Hi, Are you using the right theme version? and actually it would be very helpful if you could provide more details about your OS, please

**Comment by dukeofsoftware** [comment]
Hi! I am using sweet dark. I downloaded 3 days ago so it is the latest version. When I first downloaded 1 year ago I encountered the same issue. I managed to solve but I can't remember how I solved.
![image](https://github.com/EliverLara/Sweet/assets/89215036/9ee24650-1426-45b0-8f66-f45e1b85e4ff)
![image](https://github.com/EliverLara/Sweet/assets/89215036/682e45d3-2d01-4d81-93ab-e106df79c671)

**Comment by EliverLara** [comment]
I think you're using the wrong version of the theme for your system, please try using the version tagged wit `-v40` at the end

**Comment by dukeofsoftware** [comment]
It worked. Thank you so much!
