### ISSUE TITLE
Graphical theme issue with GNOME 46

### ISSUE THREAD

**Issue by D3vil0p3r** [EliverLara/Sweet#261]
Hello @EliverLara , after upgrading my GNOME environment in Arch Linux (VMware Virtual Machine), when I open the File Manager, the themed window appears like:
![image](https://github.com/EliverLara/Sweet/assets/83867734/9721ffca-021e-4540-be34-217645445110)

**Comment by EliverLara** [comment]
Hi @D3vil0p3r this is odd, I've just tested it in a vanilla installation of Gnome 46(Fedora 40) and it seems to be working fine:
![Captura desde 2024-03-31 13-28-18](https://github.com/EliverLara/Sweet/assets/9838260/7abaaad5-0b71-462e-852c-505713a04eed)

Could you share more details about your system, please?

**Comment by D3vil0p3r** [comment]
Sure. I am using Arch Linux. But I have a question. Did you link some gtk.css or similar files to home folder to set the theme? Or only you place the theme folder in /usr/share/themes?

**Comment by EliverLara** [comment]
Yes, I applied the gtk4 theme by using [libadwaita-theme-changer](https://github.com/odziom91/libadwaita-theme-changer), you could try using such script maybe it could work.

**Comment by D3vil0p3r** [comment]
Hello @EliverLara
I analyzed more in deep the issue. I don't think it is a theme issue. I am able to reproduce it when I use a VM (for example VMware Workstation) and I enable 3D Acceleration. If I disable it, I get the correct visualization.

Thank you for your availability.
