### ISSUE TITLE
Gnome 46: Connection-/Power pannel visual issue

### ISSUE THREAD

**Issue by MLengl** [EliverLara/Sweet#262]
# Issue 1: Connect-Power-Panel overlaps screen:
## Description
I am having my dash panel on top of the screen and when I click at the connection-/power menu it opens but will overlap the current screen.The menu is a small part at the right upper corner BUT a black intransparent filled box overlaps the rest of the screen.

## 1 expectation:
Only the usual menu is shown without overlapping the rest of the screen.

# Issue 2: Connection indicators are not shown
## description:
Opening the connection/power menu does not show indicators which element is active or not. It shows only more settings or not. But for example wifi/bluetooth can not be identified active or inactive.

## Expectations:
Colored highlight for active wifi/bluetooth/ .. 

# Screenshow (shows both)
![image](https://github.com/EliverLara/Sweet/assets/52546181/8dcbbfc2-4372-49b3-8f5b-3820804bfcec)

**Comment by EliverLara** [comment]
Hi, I'd like to know what version of the theme are you using?

**Comment by EliverLara** [comment]
Please try downloading directly from [gnome-look](https://www.pling.com/p/1253385/) you shoud use the files tagged with `-v40` and to fully apply the theme on your gnome version please try using [this script](https://github.com/odziom91/libadwaita-theme-changer)

**Comment by EliverLara** [comment]
Are you using any gnome-shell extension? and it would be very helpful if you could provide more details about you OS, please

**Comment by EliverLara** [comment]
Thanks for updating the info! the orange sliders are supposed to be that color, I'll close this as completed :)
