### ISSUE TITLE
Align Releases files with GNOME Look files

### ISSUE THREAD

**Issue by D3vil0p3r** [EliverLara/Sweet#266]
Hello @EliverLara 
I see that in GitHub Releases section of this repository, the submitted packages are not aligned with the ones you uploaded in GNOME Looks website. They have different dates. Could you please upload those updated packages also on this repo GitHub Releases section?

**Comment by D3vil0p3r** [comment]
@EliverLara

**Comment by EliverLara** [comment]
I'm sorry for the late response, I've just released a new version https://github.com/EliverLara/Sweet/releases/tag/v5.0

**Comment by D3vil0p3r** [comment]
Thank you very much
