### ISSUE TITLE
Option buttons are missing

### ISSUE THREAD

**Issue by Nesaijn** [EliverLara/Sweet#27]
This happens in both Sweet Mars and Sweet Dark. The picture should show the problem. I added a second screenshot to show how it should look like. This happens in the application Xfce4-screenshooter.
I use Manjaro with XFCE
![sweet_mars](https://user-images.githubusercontent.com/25134837/52106962-d78b7680-25f4-11e9-87de-5f20d44a4c74.png)
![how_it_should_look_like](https://user-images.githubusercontent.com/25134837/52106964-d9edd080-25f4-11e9-9148-48e7de7b1681.png)

**Comment by EliverLara** [comment]
Hi, I've tested it on my xfce desktop, but it looks good for both of your issues (firefox and this) 

![_captura de pantalla_2019-02-01_00-56-29](https://user-images.githubusercontent.com/9838260/52107701-0259d880-25bd-11e9-9d3f-15869410c88e.png)

Could you check if it's not an installation issue? just like [this](https://github.com/EliverLara/Ant-Dracula/issues/16)

**Comment by Nesaijn** [comment]
Thank you for your quick response!
My conclusion would also be that it could be an installation issue. I will test it later this day.
Thank you. :)

**Comment by Nesaijn** [comment]
Yep, the installation was the problem. Doing it manually like you described has done the job.
Sorry for that and thank you for your attention.
