### ISSUE TITLE
Kvantum Theme menu laggy if combo_menu=true

### ISSUE THREAD

**Issue by Kasi07** [EliverLara/Sweet#272]
The issue #264 persists for me after updating the theme files.
Many menus, but not all, are still very laggy and slow to load. I also notice that plasma-shell utilizes 99% of my CPU for some reason.

In the kvantum Preview I observed the following menus to be laggy:
- Push button with menu
- Standard combo box
- Editable combo box

As a temporary workaround:
I tried changing the settings a little and noticed that turning off the `combo_menu` setting eliminated the lag for me in Standard and Editable combo box but unfortunately not in the Push button with menu.

**Comment by EliverLara** [comment]
Hi, it looks good for me :

[Screencast_20241002_144853.webm](https://github.com/user-attachments/assets/b7fb0d51-65c9-48ab-b42a-1f5749d7c819)


 Did you try completely removig and reinstallig the theme?

**Comment by Kasi07** [comment]
Okay, so I reinstalled everything and it looks a little different now, but seems to work.
