### ISSUE TITLE
When will you make a release so that others can download from here?

### ISSUE THREAD

**Issue by diegovincent** [EliverLara/Sweet#31]

**Comment by zamber** [comment]
This is a bit laconic, let me elaborate.

First off - the theme is awesome. I love it's style and darkness. I have stumbled upon parts of it but finally I was sold when I saw it's the No. 1 in KDE's theme installation thingy.

What @diegovincent is asking for is to have the compiled scss files hosted on GitHub. This would allow me (and others) to just checkout the repo and pull it when there are updates but it adds a build step.

I see that the Gulpfile does only watching and does not build the project. Can I help in setting it up?

**Comment by EliverLara** [comment]
Actually this repo contains the compiled css files, what he needs is for me to make releases on github as I have done with my Ant and Nordic theme, so it's easy for users to download the theme or package it for distributions, I forgot to do it, but I will do it tomorrow, I'm sorry for forgetting it :(
