### ISSUE TITLE
some element in xfce4 wrong

### ISSUE THREAD

**Issue by denikris** [EliverLara/Sweet#32]
![Screenshot_2019-03-31_21-55-37](https://user-images.githubusercontent.com/16707606/55290629-d661a480-53ff-11e9-8b33-7da3092004d8.png)

first of all, thank you for this beautiful theme :-)

xubuntu 18.04
xfce4-panel cannot be set to semi-transparent at some indicator
make menu bar color same as xfwm4
xfce4-whiskermenu-plugin also have some element that cannot be set to semi-transparent

**Comment by EliverLara** [comment]
That's fixed with latest commits

**Comment by denikris** [comment]
thanks for the update, but i think what i expect for menu bar in xfce 4.12 is like the right side while this theme latest version is still have same color of menu bar like the left side
![bitmap](https://user-images.githubusercontent.com/16707606/61766670-e583bc80-ae0b-11e9-9923-161c747f9c1f.png)
