### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by RaghavRao** [EliverLara/Sweet#33]
Hi I love your theme but it looks a little small on a 2K display (running Xfce). I understand porting themes over to HiDPI is tedious work. Do you think this is planned for the Sweet theme? I am willing to compensate for this, how much do you think is appropriate?

**Comment by EliverLara** [comment]
Sadly for now I have no way to test that, so I hope to do it in a near future

**Comment by RaghavRao** [comment]
I can help with the testing by sending you screenshots of each build. I
could automate it
