### ISSUE TITLE
To light sliders

### ISSUE THREAD

**Issue by thekomer** [EliverLara/Sweet#38]
It's not an issue per se. But a consideration/request. I don't know how other ppl feel about it.  Would you consider making these sliders darker in Sweet-nova (Sweet Dark)? I'm using xfce. Here's a Thunar
![Thunar](https://user-images.githubusercontent.com/17909481/59555460-d448c400-8fb2-11e9-9cc6-5bbee9e29f94.png)
 screenshot. Sliders I'm talking about are above and next to orange mouse arrow. If you don't consider this to be a valid issue, just close it ;-)
Than you! :-)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, you're right, I'll try to change the color to a darker one

**Comment by thekomer** [comment]
Thank you! Don't worry about responding quickly. Take your time.

**Comment by thekomer** [comment]
Nice! I like it! :-)

**Comment by thekomer** [comment]
Nice! I like it! :-)
