### ISSUE TITLE
information bubbles inconsistent

### ISSUE THREAD

**Issue by thekomer** [EliverLara/Sweet#39]
I don't know how to call them, so I called them information bubbles :-) When I place mouse over some icon, bubble comes up with information. Anyway... some bubbles are white, some are black. I'd prefer all of them to be consistent with the theme. So something like: #181b28 .
Here are pictures... 

...with "another dark theme":
![other-dark1](https://user-images.githubusercontent.com/17909481/60029237-0a680100-96a1-11e9-8fb7-2c5347ede973.png)
![other-dark2](https://user-images.githubusercontent.com/17909481/60029241-0f2cb500-96a1-11e9-9f88-02f3cd6561c8.png)

...and with "sweet-nova":
![sweet-dark1](https://user-images.githubusercontent.com/17909481/60029246-12c03c00-96a1-11e9-9c51-380f0ec74ef7.png)
![sweet-dark2](https://user-images.githubusercontent.com/17909481/60029252-15229600-96a1-11e9-8f89-a19955cd5bf6.png)

Another dark theme is just a reference that it can be done :-) 
Cheers!

**Comment by EliverLara** [comment]
Hi, in your screenshots it seems that you are using the sweet-ambar theme(because of the accent color shown in desktop switcher widget), if so, that could be because that is not a completely dark theme, and apparently the widget is using another type of element instead of tooltips to display info.

**Comment by thekomer** [comment]
Hey there! Actually that was Sweet-nova edited. I changed accent colors to orange (per our email correspondence, maybe you remember :-}) I didn't bother to change to original Nova prior to taking those screenshots. I thought it doesn't matter since bubbles were the point.  Okay, I've made new screens with freshly downloaded Nova that has all new commits.  

![sweet-nova1_](https://user-images.githubusercontent.com/17909481/60057627-93089080-96e5-11e9-8b3c-452905ad296a.png)
![sweet-nova2_](https://user-images.githubusercontent.com/17909481/60057637-969c1780-96e5-11e9-93fc-62444e63386c.png)
![sweet-nova3_](https://user-images.githubusercontent.com/17909481/60057640-99970800-96e5-11e9-80fd-8e037154a7f5.png)
![sweet-nova4_](https://user-images.githubusercontent.com/17909481/60057650-9dc32580-96e5-11e9-9a16-5c142dba1ae8.png)
![sweet-nova5_](https://user-images.githubusercontent.com/17909481/60057654-a0be1600-96e5-11e9-9645-110bd3aa809b.png)

Yeah... they probably have different type of tooltips. That's why I sent you screenshots from another dark theme to show that all of them can be changed to a single color.  If I didn't find that theme, I wouldn't have known myself :-)
Btw, I use xfce , if it's not obvious from screenshots :-)
It's not a deal breaker of any kind. I can live with different tooltips, but OCD part of me likes things to be consistant :-)

**Comment by EliverLara** [comment]
Thank you very much for the details, Could you tell me what is your xfce version?

**Comment by thekomer** [comment]
Here you go! Xfce 4.12.3 (I's in MX linux based on Debian 9)
Tell me if there's some other info I could provide to help.

**Comment by thekomer** [comment]
Awesome! everything is consistent now. Consistently black. Don't you think it would look better if color matched theme's base color, rather then being black? Well, your choice! Thank you for fixing this.
