### ISSUE TITLE
menubar in gtk2 and gtk3 apps

### ISSUE THREAD

**Issue by denikris** [EliverLara/Sweet#43]
![g58](https://user-images.githubusercontent.com/16707606/62269775-50617300-b45e-11e9-8324-af5223dcd710.png)

above are transmission (gtk3) and thunar 1.6.x (gtk2) before i change menubar color and below is after

here's what i do:

i change files in folder **gtk-2.0** which is **gtkrc** file, by adding at the top
`# Titlebar color`
`gtk-color-scheme = "text_color:#C3C7D1\ntitlebar_bg_color:#101013"`
and edit line in **main.rc** at _line 1496_

from
`style "menubar" {`

`  # Needed to fix Firefox's menubar text`
`  bg[NORMAL]      = @dark_bg_color`

to
`style "menubar" {`

`  # Needed to fix Firefox's menubar text`
`  bg[NORMAL]      = @titlebar_bg_color`lines

then, i also modified _line 2841_ in files **gtk.css** and **gtk-dark.css** inside **gtk-3.0** folder

from
`menubar,`
`.menubar {`
`  background-color: #161925;`

to
`menubar,`
`.menubar {`
`  background-color: #101013;`

i don't know if your note in gtk-2.0 about firefox affect the display in xfce or not, but in my opinion this look better if you change it to look like this, maybe other Sweet variant also still have this menubar idk, i just use Sweet dark variant

**Comment by EliverLara** [comment]
Thank you very much for your suggestions! I have updated the theme with those changes

**Comment by denikris** [comment]
hi,
recently just download default and ambar variant, this problem also happen in sweet default(gtk2 and 3) and ambar(gtk2 only) variant, probably blue and mars too, can you also check it? sorry for my english :-)
