### ISSUE TITLE
Missing icons in Nautilus

### ISSUE THREAD

**Issue by boloped** [EliverLara/Sweet#44]
I love your theme, but the close, etc. buttons are missing in Nautilus (Sweet Dark)

**Comment by EliverLara** [comment]
Hi, Are you sure it is not an installation issue?

**Comment by EliverLara** [comment]
Do you talk about window control buttons? I mean minimize, maximize, close

**Comment by boloped** [comment]
Yes

**Comment by boloped** [comment]
Fixed it!
