### ISSUE TITLE
Dropdown menu color

### ISSUE THREAD

**Issue by minhduc0711** [EliverLara/Sweet#48]
Hi. 

I'm having this color issues with dropdown menus. Can you please take a look?

Thank you very much.

**Edit:** I'm using Chrome

![Screenshot from 2019-08-22 19-36-20](https://user-images.githubusercontent.com/34294427/63515342-d7ad7e00-c514-11e9-9012-c1dde2aa30bc.png)

**Comment by EliverLara** [comment]
Take a look at [this](https://github.com/EliverLara/Ant-Dracula/issues/4), please.

**Comment by Zzombiee2361** [comment]
But this isn't firefox. It's happening on chrome/chromium. This bug affects autocomplete dropdown of input. It does not affect other form component

**Comment by EliverLara** [comment]
This also happens with  adwaita-dark and arc-dark themes, Have you found any dark theme that does not have the issue?

![Captura de pantalla de 2019-11-08 13-13-51](https://user-images.githubusercontent.com/9838260/68504907-b747b280-022b-11ea-9c2c-7ead7b7d73e6.png)
![Captura de pantalla de 2019-11-08 13-12-27](https://user-images.githubusercontent.com/9838260/68504908-b747b280-022b-11ea-9682-0fb2ad829df4.png)

**Comment by minhduc0711** [comment]
> This also happens with adwaita-dark and arc-dark themes, Have you found any dark theme that does not have the issue?
> 
> ![Captura de pantalla de 2019-11-08 13-13-51](https://user-images.githubusercontent.com/9838260/68504907-b747b280-022b-11ea-9c2c-7ead7b7d73e6.png)
> ![Captura de pantalla de 2019-11-08 13-12-27](https://user-images.githubusercontent.com/9838260/68504908-b747b280-022b-11ea-9682-0fb2ad829df4.png)

@EliverLara I guess Chrome has the same problem for Dark themes as well. Thanks for pointing that out.
