### ISSUE TITLE
Theme not entirely applied

### ISSUE THREAD

**Issue by wordyallen** [EliverLara/Sweet#51]
![](https://i.imgur.com/ONqEOnB.gif)

I'm not sure why the colors aren't applied uniformly? Shouldn't the theme make it white everywhere? Like it does with Arc? 

I might be missing dependencies.  From `neofetch`:

OS: Arch
WM: i3
DE: none

Thanks!

**Comment by wordyallen** [comment]
I'll use another OS. I just want to load this

**Comment by EliverLara** [comment]
Hi, What do you mean?  Where does the theme not apply?

**Comment by wordyallen** [comment]
![](https://i.imgur.com/t0JI8ty.gif)

Do you see how dark arc  makes the whole window dark?  Do you see how when I apply Sweet it makes the only one part of the window white?

**Comment by EliverLara** [comment]
@wordyallen Did you receive the email I sent you?

**Comment by wordyallen** [comment]
@EliverLara yes I did. thanks you very much! Sorry for the delay in the response.
