### ISSUE TITLE
Gnome Shell Popup text color

### ISSUE THREAD

**Issue by mateuswetah** [EliverLara/Sweet#52]
Hi there, thank you for the amazing theme, 

I have on issue, not sure if it's something wrong with my installation?

![sweet_issue](https://user-images.githubusercontent.com/1184874/67243435-e5f11b00-f42d-11e9-89fa-3f8e0578e5bc.png)

My specs:

- Ubuntu 19.10, recently installed
- GNOME Shell 3.34.1

Thanks in advance!

**Comment by irenegr** [comment]
This theme is amazing, thank you.

Same specs, same problem:
Ubuntu 19.10
GNOME Shell 3.34.1

![Screenshot from 2019-10-28 09-07-59](https://user-images.githubusercontent.com/3054512/67658682-f1c76a80-f962-11e9-8a75-39c1b65c24ed.png)

PS. The same problem occurs with almost all of my dark shell themes (except Qogir-win-dark)

**Comment by EliverLara** [comment]
Hi, Thanks for reporting! I will install gnome 3.34 to fix it

**Comment by EliverLara** [comment]
That should be fixed with the last commit

**Comment by irenegr** [comment]
Solved.
Thank you.

**Comment by mateuswetah** [comment]
Tahnks, is good!
I was about to close but just notice a small detail: notification detailed text is still dark :(

![Captura de tela de 2019-11-08 21-37-22](https://user-images.githubusercontent.com/1184874/68519605-d9afef00-0270-11ea-9712-b81d2862003e.png)

**Comment by EliverLara** [comment]
@mateuswetah that should be fixed now!

**Comment by mateuswetah** [comment]
Great :)
