### ISSUE TITLE
Top Bar disappearing upon clicking the top right button on Gnome 3.34.x

### ISSUE THREAD

**Issue by jdmac87** [EliverLara/Sweet#53]
**Problem:**
Top bar keeps disappearing under particular circumstances since moving to Gnome 3.34.1.

**Replication Steps:**
Upgraded to Fedora 31 from Fedora 30, and so now on Gnome 3.34.1.
When a window is not maximised, clicking the top right button (where power and logout are) causes the top bar to disappear (approx 90% of the time).

Activities button doesn't do the same, and neither does the menu for a particular application.
Just seems to be limited to the one menu.

**Comment by jdmac87** [comment]
Thank you - I did try digging to see if I could propose a fix, but I'm not savvy with debugging Gnome themes to see what was causing.

What I did try to do, was use different variants of your Shell theme (Sweet and Sweet-Dark).
I can confirm both demonstrate the same issue.

I have tested this on multiple installations of Fedora 31/Gnome 3.34.x.

If there's any testing you need to aid the situation further, please let me know.

**Comment by EliverLara** [comment]
I have updated my fedora to version 31 with gnome 3.34, but I am not able to reproduce the issue

**Sweet**

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/9838260/68058283-34b87380-fcbe-11e9-8acc-58b51b7103be.gif)

**Sweet dark**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9838260/68058310-4732ad00-fcbe-11e9-8c82-e3098efdee00.gif)

Have you tried if it's not a issue with some gnome-shell extension?

**Comment by jdmac87** [comment]
Thanks for the response @EliverLara - I'm only using the latest Dash-to-dock, I'll try disabling and see.
Will update in next few minutes.

**Comment by jdmac87** [comment]
Looks like it might be related to dash-to-dock.

**Comment by jdmac87** [comment]
### **Ignore last comment, I've left it for historical vision**
Issue occurs when all extensions except user themes.

I am using Wayland, as per default for Fedora.
Are you (@EliverLara ) using Xorg or Wayland?

**Comment by EliverLara** [comment]
@jdmac87  I'm on wayland session as well as i'm using dash-to-dock extension. Does the issue persist with other themes?

**Comment by jdmac87** [comment]
@EliverLara I tried arc gtk theme from fedora repos and that seems to work fine.

**Comment by EliverLara** [comment]
For now, I can only keep trying to reproduce the issue

**Comment by jdmac87** [comment]
> For now, I can only keep trying to reproduce the issue

Understood, I appreciate that. Nothing you can do unless it actually manifests for you.
If I find any sort of idea on it, I'll of course drop a line on here.

Much appreciated your efforts and also your lovely theme.

**Comment by jdmac87** [comment]
@EliverLara - I think I might have narrowed the reproduction of the issue.
So, I didn't expect this to have an attribute however here goes.

I'm running my instances of Fedora 31 within a VMWare Workstation Player machine.
Host is Windows 10 Pro 1903.

If I check the option to Accelerate 3D Graphics, then the issue occurs.
Disabling this results in working.

So it seems very specifically an issue with 3D Acceleration within VMWare Workstation Player.

This is most likely, I expect, why you don't see the same result.

However, it still seems to just be this theme, but it leads me to wonder why.

Does this help reproduce the circumstances, and does it give you any ideas what might cause this?
