### ISSUE TITLE
Window buttons highlight color in Xfce 4.12

### ISSUE THREAD

**Issue by thekomer** [EliverLara/Sweet#54]
hey!

I've got problem on my Xfce4.12 (gtk2) setup (MX Linux 18.3). Active panel window buttons have black background so they are not distinguishable enough from inactive buttons.  I think they used to be purple (same as background highlight color), but that got changed along the way in some of your updates.

(I checked master branch of your theme and background color for active button is green. Also, window buttons for Nova branch in Xfce4.14 (gtk3) works okay. Purple background. So I'm pretty positive that black background in xfce4.12 is not intentional. Or, is it?)

Could you fix that?
Thanks!    

p.s. screenshot:

**Comment by thekomer** [comment]
![s2](https://user-images.githubusercontent.com/17909481/67963893-a8477b80-fbff-11e9-88d7-412449a55c41.png)

**Comment by EliverLara** [comment]
Hi, I'll check that.
