### ISSUE TITLE
Original licensing removed

### ISSUE THREAD

**Issue by MarianArlt** [EliverLara/Sweet#62]
At least your KDE SDDM theme in your Nova branch is void of all original licensing notices by David Edmundson from 2016.

    /*
     *   Copyright 2016 David Edmundson <davidedmundson@kde.org>
     *
     *   This program is free software; you can redistribute it and/or modify
     *   it under the terms of the GNU Library General Public License as
     *   published by the Free Software Foundation; either version 2 or
     *   (at your option) any later version.
     *
     *   This program is distributed in the hope that it will be useful,
     *   but WITHOUT ANY WARRANTY; without even the implied warranty of
     *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     *   GNU General Public License for more details
     *
     *   You should have received a copy of the GNU Library General Public
     *   License along with this program; if not, write to the
     *   Free Software Foundation, Inc.,
     *   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
     */

GPL doesn't mean you can just delete original creators licenses. If you really added valuable code to a file then add yourself to the license. At the bare minimum give the creator credit wherever you re-distribute his work.

**Comment by EliverLara** [comment]
Added, thanks.
