### ISSUE TITLE
[SDDM] Bad password spacing

### ISSUE THREAD

**Issue by andreasomaini** [EliverLara/Sweet#63]
# Problem

I am using Kubuntu 19.10, and I have installed Sweet's SDDM theme.
The problem is the spacing of the password's character, as you can see here:

![sddm](https://user-images.githubusercontent.com/49907041/69495539-588b6580-0ec8-11ea-8644-7d3b435f52dd.jpeg)

The password field looks way different than [this](https://github.com/EliverLara/Sweet/blob/nova/kde/sddm/preview.png)

Is it maybe just a font issue (?)

**Comment by EliverLara** [comment]
Hi, you're right, that's just a font issue.
