### ISSUE TITLE
Changing colors - titlebar

### ISSUE THREAD

**Issue by boardfish** [EliverLara/Sweet#64]
I'm tinkering with the colors in `gtk-3.0/colors.scss` in an effort to make a Solarized fork of this theme. I've been able to change lots of things so far, but there are a few things I need to iron out. 

- How can I change the fg/bg colors in the titlebar? Are these wired up to the color variables in colors.scss? 
- How can I change the colors of the close/minimize buttons? Will I need to edit the SVGs and run the Python scripts in `src` for this?

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response:
*  To change the headerbars colors you must edit  the `gtk-3.0/widgets/_header-bars.scss` file.
* To change the colors of the close/minimize buttons:

  * Update the `.svg` files under the `assets/` directory and generate the corresponding `.png` files.
  * Update the `.svg` files under the `xfwm/assets/` directory and run the `xfwm/render_assets.fish` script.
  * Update the `.svg` files under the `src/wm/` directory and run the `src/render-wm-assets.py` script.

**Comment by boardfish** [comment]
Thanks, I've managed to do this on my fork! I still need to do the buttons, but I'll raise that as a separate issue if I encounter any problems.
