### ISSUE TITLE
#panel - changing colors

### ISSUE THREAD

**Issue by boardfish** [EliverLara/Sweet#66]
It'd be nice if `$fg_color`, `$bg_color` and `$base_color` affected things more widely across the theme, but my main task for now is to theme `#panel` (i.e. the top bar and application tray in GNOME, which are black with some transparency by default). Since my own experiment resulted in me needing to reinstall my OS, I'm a little cautious with experimentation. I'm going to have a look into this myself and will report what I find here, but an easy answer would be appreciated in the meantime.

**Comment by EliverLara** [comment]
Hi, I'm sorry, if you still need it, that panel is part of the shell theme, so you need to edit the files inside the `gnome-shell/` directory.
