### ISSUE TITLE
This theme is not working with Kvantum

### ISSUE THREAD

**Issue by Joe23232** [EliverLara/Sweet#71]
So I downloaded the compressed file and I extracted it and using the Kvantum manager I selected the extracted folder but I received an error message that states to select a Kvantum folder.

How do I fix this?

**Comment by EliverLara** [comment]
Hi, the easiest way to install a theme for kvantum is to extract the theme folder under `.config/Kvantum/`, then open `kvantum-manager > change/delete theme` and select the recently installed theme.

**Comment by Joe23232** [comment]
Thanks, another issue with your theme is for some reason the taskbar and startmenu do become transparent but they are not using the blur effect, do you know how to fix this?

**Comment by EliverLara** [comment]
I think you're talking about the plasma elements, right, if so, please, make sure you've[ enabled](https://www.omgubuntu.co.uk/2018/06/how-to-enable-blur-kde-plasma-5-13) blur.

**Comment by Joe23232** [comment]
@EliverLara 

Oh ok thanks mate :)

Another question, I wanted to develop my own theme based on other people's themes.

I am in this directory `~/.local/share/plasma/desktoptheme/Sweet/`

![image](https://user-images.githubusercontent.com/34926497/73584201-f3b54280-44ea-11ea-8ea6-8aae5287073b.png)


I want to know where do I go to edit whatever I want to? For example how the start menu highlights work?
![image](https://user-images.githubusercontent.com/34926497/73586401-8c09f200-4500-11ea-9844-f4b57a827a45.png)

Or how round the buttons are

![image](https://user-images.githubusercontent.com/34926497/73586409-ae037480-4500-11ea-9a63-4ee2a08af0e6.png)

Or anything, I just want to know how do I edit other people's themes? Could you please help me out?

**Comment by EliverLara** [comment]
To change those elements, you should edit the .`svg `files inside the `widgets` folder.
