### ISSUE TITLE
Do you have an official repo?

### ISSUE THREAD

**Issue by SrSands** [EliverLara/Sweet#73]
I love this theme but the only problem I have is that I have to update it manually.
I'm on Manjaro gnome and I would love to have this theme for example in the aur, to be able to auto-update.
If you have any other repository in flatpak or in any other site I will love to know it.

**Comment by EliverLara** [comment]
It's not mine, nor official but I found [this one](https://aur.archlinux.org/packages/sweet-theme-git/) in the aur
