### ISSUE TITLE
Uncompatible with some default Apps

### ISSUE THREAD

**Issue by Rishang** [EliverLara/Sweet#74]
apps like bleach bit , vlc , gparted , zenmap are having issues with theme , they dont detect the theme for pygtk apps

**Comment by EliverLara** [comment]
Hi, you must place the theme's folder under `/usr/share/themes/` in order to take effect on those apps.

**Comment by Rishang** [comment]
Ok sir ! , It worked , also Sweet is a very nice theme thanks for making it.

**Comment by Rishang** [comment]
Also one minor issue , as pseen in image , when is save file from editos , it's font color is dark grey ,
and the font color in background is black , making harder to read a file so , please make font color white for that portion of text .


![Screenshot from 2020-03-19 18-50-36](https://user-images.githubusercontent.com/30040885/77071786-9cbfea00-6a12-11ea-898d-f1444ff436a6.png)
