### ISSUE TITLE
LightDM font size

### ISSUE THREAD

**Issue by thekomer** [EliverLara/Sweet#77]
Hey!

LightDM font size for selected user name is different from ( in my case smaller than) the rest of fonts.
(I don't know if this is important for troubleshooting: I'm using xfce4.14.)

tnx, 
komer

**Comment by EliverLara** [comment]
Hi, this theme does not provide a gdm theme

**Comment by thekomer** [comment]
Thank you for the reply. I didn't realise it has to be a separate thing. I thought it's the part of gtk3 or something similar.... My bad. You're free to close this issue if you don't plan to implement gdm for Sweet nova. :)
