### ISSUE TITLE
How to use Sweet-transparent-toolbar.tar.xz in kde(Manjaro)

### ISSUE THREAD

**Issue by Jontyshaw** [EliverLara/Sweet#81]
Today I have install your theme. It looks great. I love it. I have use this theme with Kvantum engine in kde. I want to know the effect of  Sweet-transparent-toolbar.tar.xz and how to configure it

**Comment by EliverLara** [comment]
Hi, Just extract the file under  `~/.config/Kvantum/` and then apply it using  `kvantum manager > change/delete themes > select 'sweet-transparent-toolbar'`
