### ISSUE TITLE
Can the Sweet theme be installed through PPA?

### ISSUE THREAD

**Issue by vyujitanaka** [EliverLara/Sweet#88]
Can the Sweet theme be installed through PPA? If so, can you provide a step-by-step guide on how to perform the installation using this method?

If not, I leave this tip to the developer of this incredible project. The need to have an installation via PPA is that the theme would always be updated when entering a "sudo apt update/upgrade" from the terminal.

Thank you in advance.

**Comment by EliverLara** [comment]
Hi, sorry, for now the theme does not contain any ppa
