### ISSUE TITLE
Missing (and sometimes reappearing) toolbar 

### ISSUE THREAD

**Issue by major-mayer** [EliverLara/Sweet#89]
Hi,
I really like your Sweet theme, it's one of the best themes out there.
Nevertheless i have a problem one my system using Manjaro KDE and Wayland (for multi monitor scaling options).
The problem is, that the toolbar (is it called like that) on every program is transparent and missing the icons on start.
It sometimes reappears after a while and dragging around the window, but not always.
You can still click the (invisible) icons and the window closes for example.

Here is a screenshot of the issue:
![Screenshot_20200514_223520](https://user-images.githubusercontent.com/17907799/81983411-a8efae80-9633-11ea-9975-fcd67357d8b5.png)

Edit: And another thing that i noticed is, that whenever something is transparent with this theme, it always gets this grain like on the toolbar.
Is there something that i can do against it? This also happened on my Kubuntu system, where i also enabled your theme.

Edit2 : I just tested it on X11 and the problem doesn't appear here, still worth an issue I think

**Comment by major-mayer** [comment]
Oops this is the wrong repository. Of course it belongs to the Sweet-Kde one.
Maybe someone can move the issue there

**Comment by joaulo** [comment]
Same problem here, fresh new Debian Testing installation, KDE Plasma + Kvantum.
Windows title bar is completely transparent and cannot see icons, but if I click where icons should be, it works. So it seems a visualization problem.
I don't know how fix it.

![Screenshot_20200808_164236](https://user-images.githubusercontent.com/11321019/89713215-90730400-d996-11ea-8d5d-acd6ed4e92cc.jpg)
![Screenshot_20200808_164320](https://user-images.githubusercontent.com/11321019/89713217-9537b800-d996-11ea-92c9-b90dbbfd58ba.jpg)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, Does this issue still persist for any of you?

**Comment by joaulo** [comment]
Just re-installed on Debian Testing and now it works!

**Comment by major-mayer** [comment]
Didn't happen to me anymore too, i will close this :)
