### ISSUE TITLE
Something goes wrong

### ISSUE THREAD

**Issue by LeVan146** [EliverLara/Sweet#9]
![screenshot from 2018-09-14 18-48-21](https://user-images.githubusercontent.com/39160607/45548542-ceb92480-b84e-11e8-91ee-19e9e916e4bc.png)
Hello, I would be grateful if you could help me with this issue (please look my screenshot). I have no an idea to fix it.
Thanks

**Comment by riesinger** [comment]
This theme requires GTK+3.20 or later, Ubuntu 16.04 (which you seem to be on) only has GTK+3.16. I suggest you upgrade to Ubuntu 18.04.01, which is also LTS
