### ISSUE TITLE
Sweet Dark: dotted lines on scrollable windows

### ISSUE THREAD

**Issue by ClaudiaSilver** [EliverLara/Sweet#90]
I've noticed that there are dotted lines visible whenever a window is scrollable (see screenshot).
![Screenshot from 2020-05-17 19-00-14](https://user-images.githubusercontent.com/12713363/82156066-fd33a200-9870-11ea-96b0-d622923003ee.png)

Is there a fix for this? 
Thank you very much for creating such a beautiful theme!

**Comment by EliverLara** [comment]
Hi, that's not really an issue, it's an indicator that a content is scrollable

**Comment by ClaudiaSilver** [comment]
Thank you, I didn't realise. I found a way to fix it. Thank you very much for the beautiful theme and icons!
