### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by mirismaili** [EliverLara/Sweet#91]
Hello,
Thank nice theme.

Where is the light version of the theme?
***
_I use KDE (Kubuntu) and I used its default theme installer. I didn't see the light version of the theme when I was installing it._

![image](https://user-images.githubusercontent.com/15800189/83098601-5c3eb580-a0c0-11ea-84f1-6be6c5ff857a.png)

**Comment by EliverLara** [comment]
Hi, I'm sorry for the late response, for now the light theme is not available for KDE yet.
