### ISSUE TITLE
Pop!_OS's notification shade is white when using the Sweet Dark theme

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [EliverLara/Sweet#93]
With the Sweet Dark theme
![Screenshot from 2020-07-03 14-08-19](https://user-images.githubusercontent.com/46287209/86493344-d0f7b600-bd36-11ea-8e40-186213355149.png)
With Pop!_OS's dark theme
![Screenshot from 2020-07-03 14-09-45](https://user-images.githubusercontent.com/46287209/86493385-fbe20a00-bd36-11ea-862b-1d1727274e49.png)
The search bar in the activities menu is also white with the Sweet Dark theme selected.

**Comment by MarshmelloSUCKS** [comment]
Notifications are also white with Sweet Dark

**Comment by EliverLara** [comment]
Hi, It seems that you have not applied the shell theme, you have to install [this](https://extensions.gnome.org/extension/19/user-themes/) extension and then select 'sweet' in the shell section of tweaks.

**Comment by MarshmelloSUCKS** [comment]
That worked. Thanks!
