### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by ltest-dev** [EliverLara/Sweet#97]
Hi,
Sorry I'm not really good at this. How do I switch from the default colors (white/green) to one of the other (seen in README picture) ?
I would like the dark/purple one, but at the moment I found how to get dark theme by switching `gtk-application-prefer-dark-theme` to 1, but I can't find for the purple part.
Thanks

**Comment by tmarti2** [comment]
Ok I just found out there are many zip available in the releases page, my bad, I installed it via AUR.
