### ISSUE TITLE
Screen Locking to sync sddm

### ISSUE THREAD

**Issue by RickyElune** [EliverLara/Sweet#99]
I can change the login screen by sddm, there is no problem. I want to learn How to change lock screen theme? I've set globle theme and plasma style 'Sweet' but not work. It will still use breath theme when screen locking so I guess it's not part of your work.
I know these are two separate applications, developed independently.

1: SDDM (Simple Desktop Display Manager)
2: Plasma shell (Plasma 5’s desktop shell)

The lock screen is part of the Plasma shell and uses the same theme as it.
SDDM is the login manager and uses it’s own theme engine.
So is there any way to make lock screen the same as sddm login theme? That would be really cool thanks!

**Comment by EliverLara** [comment]
I've improved the kde lockscreen and now it matches sddm.
